apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: csb-demo-monitor
  name: csb-demo-monitor
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: camel-example-spring-boot-actuator-http-metrics

